spring:
  application:
    name: emoji
  datasource:
    username: emoji_manager
    password: 123456
    url: jdbc:mysql://59.110.93.150:3306/db_emoji?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&userSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  data:
    redis:
      host: 59.110.93.150
      port: 6379
      password: H@Ld9mdD(buU

server:
  port: 8081

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml

