spring:
  application:
    name: emoji
  datasource:
    username: emoji_manager
    password: 123456
    url: jdbc:mysql://59.110.93.150:3306/db_emoji?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&userSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
